# Generated by Django 3.2.4 on 2022-01-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=140)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=10000)),
            ],
        ),
    ]
